package com.blockflow.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity representing a Product in the BlockFlow system.
 * Maps to the "products" table in the database.
 */
@Entity
@Table(name = "products")
@Data
@NoArgsConstructor
@AllArgsConstructor
@lombok.Builder
public class Product {

    /**
     * Unique identifier for the product.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the product.
     * Cannot be null and must not exceed 100 characters.
     */
    @NotBlank(message = "Name is required")
    @Size(max = 100, message = "Name cannot exceed 100 characters")
    @Column(nullable = false, length = 100)
    private String name;

    /**
     * Dimensions of the product (e.g., "600x200x100mm").
     */
    @NotBlank(message = "Dimensions are required")
    private String dimensions;

    /**
     * Price per unit of the product.
     * Must be positive and have 2 decimal places.
     */
    @NotNull(message = "Price is required")
    @Positive(message = "Price must be positive")
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal pricePerUnit;

    /**
     * Quantity of stock available.
     * Must be zero or greater.
     */
    @NotNull(message = "Stock quantity is required")
    @Min(value = 0, message = "Stock quantity cannot be negative")
    @Column(nullable = false)
    private Integer stockQuantity;

    /**
     * Description of the product.
     * Optional, max 500 characters.
     */
    @Size(max = 500, message = "Description cannot exceed 500 characters")
    @Column(length = 500)
    private String description;

    /**
     * Weight of the product in kg.
     * Must be positive.
     */
    @NotNull(message = "Weight is required")
    @Positive(message = "Weight must be positive")
    @Column(precision = 10, scale = 2)
    private BigDecimal weight;

    /**
     * Category of the product.
     */
    private String category;

    /**
     * Number of times the product has been viewed.
     */
    @Builder.Default
    @Column(nullable = false)
    private Long viewCount = 0L;

    /**
     * Timestamp when the product was created.
     * Auto-generated.
     */
    @Column(updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the product was last updated.
     * Auto-updated.
     */
    private LocalDateTime updatedAt;

    /**
     * Sets the creation timestamp before persisting.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;
}
